version: "3"
services:
    mkdocs:
        volumes:
            - ./docs:/app
        working_dir: /app
        labels:
            - com.dnsdock.alias=docs.popochiu.loc
        build:
            context: .
            dockerfile: Dockerfile
        command: serve -a 0.0.0.0:80