site_name: Popochiu Documentation
site_description: Home to the documentation of Popochiu, a Godot plugin to build point-and-click adventure games.
site_author: The Carenalgas Community
copyright: Copyright (c) 2024 - The Carenalgas Community
repo_url: https://github.com/carenalgas/popochiu/
edit_uri: edit/develop/docs/src/
docs_dir: src
site_dir: dist
site_favicon: assets/images/_other/theme/favicon.ico
theme:
  name: readthedocs
  titles_only: true
  logo: assets/images/_other/theme/logo.svg
extra_css:
  - assets/css/custom.css
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/tomorrow-night-bright.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/markdown.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/bash.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/yaml.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/json.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/dockerfile.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/makefile.min.js
  - assets/js/gdscript.min.js
  - assets/js/custom.js
markdown_extensions:
  - admonition
  - attr_list
  - fontawesome_in_markdown
  - def_list
plugins:
  - search
  - mkdocs-nav-weight
  - mermaid2:
      version: 11.4.1
  - redirects:
      redirect_maps:
        # #383: The section on creating a game stub has been
        #       promoted as the "How to develop a game" section.
        'getting-started/creating-a-game-stub/add-an-inventory-item.md' : 'how-to-develop-a-game/add-an-inventory-item.md'
        'getting-started/creating-a-game-stub/conclusions.md' : 'how-to-develop-a-game/conclusions.md'
        'getting-started/creating-a-game-stub/create-characters.md' : 'how-to-develop-a-game/create-characters.md'
        'getting-started/creating-a-game-stub/create-the-first-room.md' : 'how-to-develop-a-game/create-the-first-room.md'
        'getting-started/creating-a-game-stub/customize-the-game-ui.md' : 'how-to-develop-a-game/customize-the-game-ui.md'
        'getting-started/creating-a-game-stub/game-setup.md' : 'how-to-develop-a-game/game-setup.md'
        'getting-started/creating-a-game-stub/index.md' : 'how-to-develop-a-game/index.md'
        'getting-started/creating-a-game-stub/introduction.md' : 'how-to-develop-a-game/introduction.md'
        'getting-started/creating-a-game-stub/script-your-first-dialogue.md' : 'how-to-develop-a-game/script-your-first-dialogue.md'
        'getting-started/creating-a-game-stub/use-inventory-items.md' : 'how-to-develop-a-game/use-inventory-items.md'
        # #383: The section on advanced techniques is now
        #       called "Advanced topics" and moved to the root level.
        'how-to-develop-a-game/advanced-techniques/advanced-animations.md' : 'advanced-topics/advanced-animations.md'
        'how-to-develop-a-game/advanced-techniques/change-text-to-gibberish.md' : 'advanced-topics/change-text-to-gibberish.md'
        'how-to-develop-a-game/advanced-techniques/character-anti-glide-feature.md' : 'advanced-topics/character-anti-glide-feature.md'
        'how-to-develop-a-game/advanced-techniques/character-scaling.md' : 'advanced-topics/character-scaling.md'
        'how-to-develop-a-game/advanced-techniques/extending-customizing-popochiu.md' : 'advanced-topics/extending-customizing-popochiu.md'
        'how-to-develop-a-game/advanced-techniques/game-state-saving-and-loading.md' : 'advanced-topics/game-state-saving-and-loading.md'
        'how-to-develop-a-game/advanced-techniques/guis.md' : 'advanced-topics/guis.md'
        'how-to-develop-a-game/advanced-techniques/index.md' : 'advanced-topics/index.md'
        'how-to-develop-a-game/advanced-techniques/localization.md' : 'advanced-topics/localization.md'