site_name: Popochiu Documentation
site_description: Home to the documentation of Popochiu, a Godot plugin to build point-and-click adventure games.
site_author: The Carenalgas Community
copyright: Copyright (c) 2024 - The Carenalgas Community
repo_url: https://github.com/carenalgas/popochiu/
edit_uri: edit/develop/docs/src/
docs_dir: src
site_dir: dist
site_favicon: assets/images/_other/theme/favicon.ico
theme:
  name: readthedocs
  titles_only: true
  logo: assets/images/_other/theme/logo.svg
extra_css:
  - assets/css/custom.css
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/tomorrow-night-bright.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/markdown.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/bash.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/yaml.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/json.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/dockerfile.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/makefile.min.js
  - assets/js/gdscript.min.js
  - assets/js/custom.js
markdown_extensions:
  - admonition
  - attr_list
  - fontawesome_in_markdown
plugins:
  - search
  - mkdocs-nav-weight
  - mermaid2
